# YAML Linting Configuration for AlgoAssistant
extends: relaxed

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  key-duplicates: enable
  trailing-spaces: enable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
  document-start: disable
  document-end: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: enable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
