# Base image
FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && pip install redis

COPY . .

# Default command to start web service
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"] 